adding more language to security consideration
SpencerDawkins/net-collab-rqmts pull request #48
Opened 2024-06-04 14:29 UTC by sridharangirish91

2024-06-04 16:23 UTC, boucadair requested changes

2024-06-04 16:23 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +It is RECOMMENDED toencrypt or obfuscate the metadata information so it is only availableto hosts and to authorized network elements. The method ofencryption or obfuscation is not described in this d
```suggestion
It is recommended to encrypt or obfuscate the metadata information so it is only available to hosts and to authorized network elements. The method of encryption or obfuscation is not described in this document but rather in other documents describing how this metadata is encoded and exchanged amongst hosts and network elements. The privacy implications of revealing metadata to network elements need to be thoroughly analyzed. This analysis should ensure that any exposure of metadata does not compromise user privacy or allow unauthorized entities to infer sensitive information about the data being transmitted while maintaining minimal resource consumption.
```

2024-06-04 16:25 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +It is RECOMMENDED toencrypt or obfuscate the metadata information so it is only availableto hosts and to authorized network elements. The method ofencryption or obfuscation is not described in this d
Thanks Med!

2024-06-05 09:59 UTC, tireddy2 approved these changes

2024-06-05 16:02 UTC, John-Kaippallimalil approved these changes

2024-06-06 19:39 UTC, sridharangirish91 commented
@boucadair - I think this pr requires your approval to merge since your review is still pending. Please can you approve if everything looks good?

2024-06-07 05:26 UTC, boucadair approved these changes

2024-06-07 05:26 UTC, merged