updates for issue#68
SpencerDawkins/net-collab-rqmts pull request #69
Opened 2024-09-06 00:44 UTC by John-Kaippallimalil

2024-09-11 23:38 UTC, danwing approved these changes

2024-09-12 07:41 UTC, boucadair requested changes

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +{{Figure-netshaper}} shows a bottleneck (access) Router on the path of packets from Server to Client.
```suggestion
{{Figure-netshaper}} shows a bottleneck (access) router on the path of packets from Server to Client.
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +A network shaper in the Router manages QoS of flows of multiple users and can buffer (delay), discard or apply other flow control rules. Application layer signaling and feedback between client – serv
```suggestion
A network shaper in the router manages QoS of flows of multiple users and can buffer (delay), discard, or apply other flow control rules. Application layer signaling and feedback between Client – Server (A – in the figure) adjust transmission rate over a period of several RTTs using feedback and congestion control algorithms.
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +Network shapers observe flows and apply policies to maximize performance but is not aware if there is a preference for one flow (UDP 4-tuple) over another flow belonging to the same user and network
```suggestion
Network shapers observe flows and apply policies to maximize performance but are not aware whether  there is a high preference for one flow (UDP 4-tuple) over another flow belonging to the same user and network attachment (e.g., a subscriber connection, a 3GPP PDU Session. See {{net-attach}} for more details).
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +The client can provide the (access) Router with preferences of which flow (UDP 4-tuple) has relative priority among flows of that network attachment using H2N (C - in figure).
```suggestion
Clients may provide an (access) router with preferences of which flow (UDP 4-tuple) has relative priority among flows of that network attachment using H2N (C - in Figure).
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +The client may also provide information to the (access) Router to drop lower priority marked packets of a flow (UDP 4-tuple) temporarily which can in turn redirect bandwidth to other flows of that ne
```suggestion
Clients may also provide information to an (access) router to drop, when resources are congested,  'lower priority'-marked packets of a flow (UDP 4-tuple) temporarily which can in turn allocate bandwidth to other flows of that same network attachment.
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +Streaming media packets carry audio or video between server and client.
```suggestion
Streaming media packets carry audio or video between servers and clients.
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +REQ-PACKET-PRIORITY: Packet priority relative to other packets in the transport flow (UDP 4-tuple).
```suggestion
REQ-PACKET-PRIORITY: Packet priority relative to other packets within the same transport flow (UDP 4-tuple).
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +REQ-PACKET-DELAY: Metadata to indicate whether the packet can tolerate delay.
```suggestion
REQ-PACKET-DELAY: Metadata to indicate whether a packet can tolerate delay.
```

2024-09-12 07:41 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +For example, an on-going file copy operation flow (UDP 4-tuple) a remote desktop user can tolerate more delay than the flow carrying graphics updates.
```suggestion
For example, an on-going file copy operation flow (UDP 4-tuple) of a remote desktop user can tolerate more delay than the flow carrying graphics updates.
```

2024-09-12 16:14 UTC, danwing approved these changes

2024-09-12 17:56 UTC, boucadair approved these changes

2024-09-12 19:31 UTC, sridharangirish91 approved these changes

2024-09-12 19:31 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +The client can provide the (access) Router with preferences of which flow (UDP 4-tuple) has relative priority among flows of that network attachment using H2N (C - in figure).
Are we delving into inter-flow priorities, outside of the same UDP 4-tuple? I thought we mindfully wanted to move away due to a lot of complexities.

2024-09-12 19:31 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +## Streaming and Interactive Media {#uc-media}
IMHO, Even if the requirements are overlapping, Streaming and Interactive Media should be separate items, given they are 2 big use cases that comprise of most of the internet traffic. On the other hand, we can merge interactive media, accommodate delay and mixed traffic into one.

2024-09-12 19:31 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +## Mixed-Traffic and User Preferences {#uc-preferences}
User Preference might not belong here given that is agnostic of the traffic type but is an end user option. I am not sure if combining these 2 makes sense

2024-09-12 19:31 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +### Delay Tolerance between Flows (Inter-flow) {#interflow-delay}
Again, we should refrain from any inter-flow discussions IMO.

2024-09-12 19:32 UTC, danwing commented
Incorporated via #70.

2024-09-12 19:50 UTC, merged