describe mis-marking metadata as a mitigation for traffic analysis, and that there are different threat models. Unfortunately the line needed to be wrapped, so 'diff' is awkward
SpencerDawkins/net-collab-rqmts pull request #73
Opened 2024-09-12 22:55 UTC by danwing

2024-09-13 08:25 UTC, boucadair requested changes

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +it is only available to the server, client and authorized network
```suggestion
it is only available to the server, client, and authorized network
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +this document but rather in other documents describing how this
```suggestion
this document but rather in other documents that specify how this
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +metadata is encoded and exchanged amongst client, server and network
```suggestion
metadata is encoded and exchanged amongst client, server, and network
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +metadata in some packets.
```suggestion
metadata in some packets, add some randomness to avoid recurrent traffic patterns, etc.
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +mitigate traffic analysis, the sender might purposefully mis-mark
```suggestion
mitigate traffic analysis, the sender might, for example, purposefully mis-mark
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +consumption. There is a tension between resource consumption of such
```suggestion
consumption. There is a tension between resource consumption (and thus efficiency) of such
```

2024-09-13 08:25 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +model; the threat of a network provider building a subscriber profile of viewed video content
```suggestion
model ({{Section 7.4 of RFC6973}}); the threat of a network provider building a subscriber profile of viewed video content
```

2024-09-13 15:14 UTC, sridharangirish91 approved these changes

2024-09-16 05:55 UTC, boucadair approved these changes

2024-09-17 05:32 UTC, boucadair commented
There is redundant text from various merges. Please see #75. Thanks.

2024-09-17 18:50 UTC, merged