fold long lines so our subsequent diffs are more sensible
SpencerDawkins/net-collab-rqmts pull request #74
Opened 2024-09-13 00:01 UTC by danwing

2024-09-13 08:31 UTC, boucadair requested changes

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +wireless/access router to delay or discard packets of lower priority
```suggestion
access router to delay or discard packets of lower priority
```

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +: Refers in this document to QoS management at the
```suggestion
: Refers in this document to QoS management at an
```

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +the downstream packet (B – in figure).  The requirements for this
```suggestion
the downstream packet (B – in the figure).  The requirements for this
```

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +Figure).  Clients may also provide information to an (access) router
```suggestion
the figure).  Clients may also provide information to an (access) router
```

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +{{Figure-conn-flow}} shows "Client-1" and "Client-2" that negotiate
```suggestion
{{Figure-conn-flow}} shows "Client-1" and "Client-2" which negotiate
```

2024-09-13 08:31 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +focuses on on-path collaboration signals that apply to data units
```suggestion
focus on on-path collaboration signals that apply to data units
```

2024-09-13 15:13 UTC, sridharangirish91 approved these changes

2024-09-16 05:57 UTC, boucadair approved these changes

2024-09-17 00:15 UTC, merged