My attempt at issue #76: client signals and API requirement
SpencerDawkins/net-collab-rqmts pull request #79
Opened 2024-09-18 18:45 UTC by danwing

2024-09-18 20:04 UTC, John-Kaippallimalil commented
Updates to the use case address my offline comments on 4.3

2024-09-18 20:33 UTC, John-Kaippallimalil requested changes
On line 508 "Network Collaboration signaled in IPv6 Hop-by-Hop", it may be better to not indicate IPv6 HbH as it is a solution.

2024-09-19 00:47 UTC, danwing commented
> Updates to the use case address my offline comments on 4.3

If this fixes #76, please close #76.

2024-09-19 05:36 UTC, boucadair requested changes
Looks good. Only minor nits. thanks

2024-09-19 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +markings are supported by the ISP (e.g., encoded into IPv6 Flow Label,
```suggestion
markings are supported by the ISP's network (e.g., encoded into IPv6 Flow Label,
```

2024-09-19 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +UDP Option, DSCP).  Then it can indicate to the ISP that a
```suggestion
UDP Option, or DSCP).  Then it can indicate to the ISP's network that a
```

2024-09-19 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +using a single or a set of API(s) independent of the channels that
```suggestion
using a single or a set of APIs independent of the channels that
```

2024-09-19 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +if one single channel is used so that any application can consume
```suggestion
if one single channel is used so that any application on a client can consume
```

2024-09-19 14:13 UTC, John-Kaippallimalil approved these changes
Addresses the main aspects for use case 4.3

2024-09-19 16:10 UTC, boucadair approved these changes

2024-09-19 16:13 UTC, merged