Added Impact to the use cases to justify requirements.
SpencerDawkins/net-collab-rqmts pull request #87
Opened 2024-09-20 00:57 UTC by sridharangirish91

Created a section to define all requirements and link them in the use cases for easier read.
Reworded a few things

2024-09-20 05:36 UTC, boucadair requested changes

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +## System-Considerations
```suggestion
## System Considerations
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +: An on-path observer obtains no additional information about the IP
```suggestion
: An on-path observer obtains (or gleans) no additional information about the IP
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +: Leveraging previous experience {{?RFC9049}}, the folliwing is not
```suggestion
: Leveraging previous experience {{?RFC9049}}, the following is not
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +  * Reveal server identity.
```suggestion
  * Reveal the server identity.
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +: The metadata other state information that a wireless router has to
```suggestion
: The metadata and any other related state information that a network element (router) has to
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +maintain for each additional media flow it handles should be very low
```suggestion
maintain for each additional flow it handles should be very low
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +flow.
```suggestion
flow from within the same host.
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +The client may indicate this preference to the network by selecting
```suggestion
The client may indicate this preference to a network by selecting
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +  better in challenging network and during reactive events ensuring better user experience.
```suggestion
  better in resource-constrained networks and during reactive events ensuring better user experience.
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +in change in priorities for the same type of traffic a single server sends, based on the user/client.
```suggestion
in change in priorities for the same type of traffic that a single server sends, based on the user/client.
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +    the metadata the server sends still remains the same for all the connections.
```suggestion
    the metadata that the server sends still remains the same for all the connections.
```

2024-09-20 05:36 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +    Impact: By identifying packets that can be dropped, congestion can be reduced leading
```suggestion
    Impact: By identifying packets that tolerate being dropped, congestion can be reduced leading
```

2024-09-20 14:26 UTC, boucadair commented
Thanks.

For "REQ-METADATA-ACCURACY", please see my comment to Dan at #86.

2024-09-20 16:09 UTC, John-Kaippallimalil commented
The main body of the draft now refers to 3 requirements (REQ-MEDIA-AV-SEPARATE; REQ-PAYLOAD-CLIENT-DECIDES, REQ-MEDIA-KEYFRAME) that are in the Appendix. This blurs the line on what sections in the Appendix are normative and informative. As a partial remedy, I have made 2 updates  (see my commits above) to indicate that these requirements are "enhanced".

2024-09-20 16:18 UTC, sridharangirish91 commented
> The main body of the draft now refers to 3 requirements (REQ-MEDIA-AV-SEPARATE; REQ-PAYLOAD-CLIENT-DECIDES, REQ-MEDIA-KEYFRAME) that are in the Appendix. This blurs the line on what sections in the Appendix are normative and informative. As a partial remedy, I have made 2 updates (see my commits above) to indicate that these requirements are "enhanced".

Hi John, thanks for the text. I agree with REQ-MEDIA-AV-SEPARATE and REQ-MEDIA-KEYFRAME but I doubt if REQ-PAYLOAD-CLIENT-DECIDES causes any issue with traffic analysis. I have moved the statements you have made into the requirements definition itself to keep the main body short and succinct while keeping the remedy in place as well.

2024-09-20 17:51 UTC, John-Kaippallimalil commented
Hi Sridhar, Re: traffic analysis comment may apply for QUIC - where a the sender may schedule packets in any order (RR, priority, deadline, or even mix multiple media types in different FRAMES of the same packet). Plus there is the option to add chaff packets or stuff packets to not be able to detect based on size/frequency. This metadata should obviously not be used where effort is being taken to mask it from middleboxes in the network. On the other hand RTP is different (except if it is RoQ).

Having this kind of dependency between Appendix and main body is not ideal in my view. The gist of the impact/effect on other parts of the main body should be described there, as otherwise its hard for a reader to figure out what the impact would be to realize that requirement. Its fine if the preference is to to keep more of the details in the Appendix.

2024-09-20 18:16 UTC, danwing commented
> Hi Sridhar, Re: traffic analysis comment may apply for QUIC - where a the sender may schedule packets in any order (RR, priority, deadline, or even mix multiple media types in different FRAMES of the same packet). Plus there is the option to add chaff packets or stuff packets to not be able to detect based on size/frequency. This enhanced metadata should obviously not be used where effort is being taken to mask it from middleboxes in the network. On the other hand RTP is different (except if it is RoQ).

Seems best to discuss once in Security Considerations (or Privacy Considerations) section, which we already discuss at https://github.com/SpencerDawkins/net-collab-rqmts/blob/main/draft-kwbdgrr-tsvwg-net-collab-rqmts.md#privacy-considerations-privacy

2024-09-20 19:27 UTC, sridharangirish91 commented
> The main body of the draft now refers to 3 requirements (REQ-MEDIA-AV-SEPARATE; REQ-PAYLOAD-CLIENT-DECIDES, REQ-MEDIA-KEYFRAME) that are in the Appendix. This blurs the line on what sections in the Appendix are normative and informative. As a partial remedy, I have made 2 updates (see my commits above) to indicate that these requirements are "enhanced".

If that's the case, then we can mention media streaming in extended use case as well, where we go little deeper into the use case and explain the extended requirements there while keeping the basic ones in the main section of the draft.

We can combine 1 and 3 in media streaming as just a way to prioritize different traffic differently and least priority ones can tolerate loss. We can then move 2 and add a use case where we can get into audio video separately as well as key frame there.
Alternatively, we could move CLIENT-PAYLOAD-DECIDES to the main doc and keep 2 there. Given AV and KeyFrame requirements are not required for Client-payload-decides and doesn't have any traffic analysis complications, it could be a valuable client-to-network signal in the main doc too.

2024-09-20 19:53 UTC, sridharangirish91 commented
@John-Kaippallimalil @danwing - Updated the text in the latest commit to keep extended use cases and requirements contained in the appendix.

2024-09-20 20:11 UTC, John-Kaippallimalil approved these changes
HI Sridhar,
This revision looks great. Thanks for the updates.

2024-09-20 20:18 UTC, danwing approved these changes

2024-09-20 20:28 UTC, John-Kaippallimalil approved these changes
Looks good.

2024-09-23 05:56 UTC, boucadair approved these changes

2024-09-23 06:05 UTC, merged