intro: remove audio/video in favor of just saying 'packet behavior preference', and include citation of unreliable QUIC which, like RTP, would benefit from this.  We had not previously cited unreliable QUIC.
SpencerDawkins/net-collab-rqmts pull request #89
Opened 2024-09-20 20:16 UTC by danwing

2024-09-20 20:29 UTC, sridharangirish91 requested changes

2024-09-20 20:29 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +signaling the network can only indiscriminately drop (or delay)
```suggestion
signaling, the network can only indiscriminately drop (or delay)
```

2024-09-20 20:29 UTC, sridharangirish91 commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +packets.  With such capability loss-tolerant and delay-tolerant
```suggestion
packets.  With such capability, loss-tolerant and delay-tolerant
```

2024-09-20 21:03 UTC, sridharangirish91 approved these changes

2024-09-23 05:53 UTC, boucadair approved these changes

2024-09-23 15:52 UTC, merged