Reducing length of Server-Network metadata while keeping the message …
SpencerDawkins/net-collab-rqmts pull request #94
Opened 2024-09-25 00:21 UTC by sridharangirish91

…consistent

2024-09-25 01:42 UTC, danwing commented
github considers every line to have changed.  Here is an (easier) side-by-side diff via RFCDIFF, https://author-tools.ietf.org/api/iddiff?url_1=https://SpencerDawkins.github.io/net-collab-rqmts/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt&url_2=https://SpencerDawkins.github.io/net-collab-rqmts/sridharanr/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt

2024-09-25 01:59 UTC, danwing requested changes

2024-09-25 01:59 UTC, danwing commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +in {{sys-considerations}}. Privacy {{privacy}} requires that metadata should not provide
```suggestion
in {{sys-considerations}}. Privacy ({{privacy}}) requires that metadata should not provide
```

2024-09-25 01:59 UTC, danwing commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +Research (e.g., {{5G-Octopus}}) indicates that media applications can achieve better QoE
```suggestion
Research (e.g., {{5G-Octopus}}) indicates that media applications can achieve better Quality of Experience (QoE)
```

IETF likes acronym expanded on first use. We don't use QoE later, but it's useful to have **QoE** in the document if someone searches for it.

2024-09-25 01:59 UTC, danwing commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +flows belinging to the same user and network attachment (e.g., a subscriber connection,a 3GPP PDU
```suggestion
flows belonging to the same user and network attachment (e.g., a subscriber connection, a 3GPP PDU
```

2024-09-25 01:59 UTC, danwing commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +‘lower priority’-marked packets of a flow (UDP 4-tuple) temporarily during congestion,
```suggestion
‘lower priority’-marked packets of a flow (UDP 4-tuple) during Reactive Management,
```

2024-09-25 01:59 UTC, danwing commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +allowing bandwidth allocation to other flows of the same network attachment.
```suggestion
allowing bandwidth allocation to other packets of the same UDP 4-tuple.
```

2024-09-25 07:34 UTC, boucadair commented
I like the changes overall, but given that we are not sure that everyone understands what we are trying to do, I suggest we leave the elaborated version (OLD) as it providers readers with explicit details. 

We can consider merging this PR in future versions. Thanks.

2024-09-25 21:52 UTC, closed without merging

2024-09-26 09:06 UTC, boucadair commented
Thanks @sridharangirish91. You may keep the PR open, though.

2024-09-26 12:33 UTC, sridharangirish91 commented
> Thanks @sridharangirish91. You may keep the PR open, though.