remove unused terminology
SpencerDawkins/net-collab-rqmts pull request #99
Opened 2024-09-25 21:21 UTC by danwing

Remove Discard Preference, Intentional Management, Traffic Shaping.  

Of those, only Discard Preference was used, and only in the abstract! The others 
were not used at all.

2024-09-25 21:51 UTC, sridharangirish91 approved these changes

2024-09-26 09:10 UTC, boucadair requested changes
We don't need to restrict the direction at the stage. It is not easy for a reader to digest why per-* is possible for a given direction only.

2024-09-26 09:10 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +of a connection and thus can be exchanged once or as needed. This is communicated per flow (i.e., UDP 4-tuple) between client and network.  This is sent from client to network.
```suggestion
of a connection and thus can be exchanged once or as needed. This is communicated per flow (i.e., UDP 4-tuple) between client and network.
```

2024-09-26 09:10 UTC, boucadair commented on draft-kwbdgrr-tsvwg-net-collab-rqmts.md
> +the nature and characteristics of the traffic each packet carries. This needs to be communicated on a per packet basis. This is sent from server to network.
```suggestion
the nature and characteristics of the traffic each packet carries. This needs to be communicated on a per packet basis.
```

2024-09-26 13:38 UTC, John-Kaippallimalil commented
Good to remove unused terminology. Changes look good.

2024-09-26 16:50 UTC, boucadair approved these changes
Thanks, Dan.

2024-09-26 17:21 UTC, merged